name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build 
      run: docker build -t helloworld .
    - name : Run
      run : docker run --rm --name helloworldrun helloworld
      
      
